### ISSUE TITLE
Build Instructions?

### ISSUE THREAD

**Issue by Carbolemons** [lemonypancakes/origins-bukkit#15]
### Minecraft Server's Version and Software

Hey! I was looking to use / modify this plugin. I have a few questions, if you don't mind!
- How do you go about building this maven project? 
- What IDE did you use for this? 
- Are there any secret dependencies? 

Any other resources we could use for this?

Thank you for taking the time to make this! It's a nice plugin :)

### Plugin's Version

v1_18_R1 

Spigot 1.18.1

### Bug Description

Request for Build Instructions

### To Reproduce

Clone the git repository and build the plugin

### Additional Information

- Request for Build Instructions
Thank you for taking the time to make this! It's a nice plugin :)

**Comment by lemonypancakes** [comment]
Do you have build tools installed? If not, follow this tutorial on how to: https://www.youtube.com/watch?v=QdV-3OtXcPY. Install the spigot versions 1.17.1 and 1.18 using the spigot build tools.

**Comment by Carbolemons** [comment]
Indeed. I seem to missing the dependency for PacketWrapper. Do you have instruction on how to build this?

**Comment by lemonypancakes** [comment]
Download the latest PacketWrapper here: https://ci.dmulloy2.net/job/PacketWrapper/
Then add a libs folder in your java project and add PacketWrapper inside the "libs" directory.
(e.g directory) <systemPath>${basedir}/libs/PacketWrapper #71.jar</systemPath>

**Comment by Carbolemons** [comment]
Thank you for your quick responses! That works now, however I guess I am still having issues importing Spigot 1.17.1 and Spigot 1.18

After I generate and install the Spigot versions, where do I add them in the project? I hope this makes sense

**Comment by lemonypancakes** [comment]
Oh. You need to install the remapped spigot version of spigot 1.17.1 and 1.18 using spigot build tools.

**Comment by Carbolemons** [comment]
Alrighty. I was able to build it. The target jar is in the compile/target/Origins-Bukkit (build).jar correct? When starting the server, I am getting a specific error

It loads in correctly, but breaks at listeners.player.JoinEventListener.onJoin

```
[21:04:47 INFO]: [Origins-Bukkit]    ___       _       _                 ____        _    _    _ _
[21:04:47 INFO]: [Origins-Bukkit]   / _ \ _ __(_) __ _(_)_ __  ___      | __ ) _   _| | _| | _(_) |_
[21:04:47 INFO]: [Origins-Bukkit]  | | | | '__| |/ _` | | '_ \/ __|_____|  _ \| | | | |/ / |/ / | __|
[21:04:47 INFO]: [Origins-Bukkit]  | |_| | |  | | (_| | | | | \__ \_____| |_) | |_| |   <|   <| | |_
[21:04:47 INFO]: [Origins-Bukkit]   \___/|_|  |_|\__, |_|_| |_|___/     |____/ \__,_|_|\_\_|\_\_|\__|
[21:04:47 INFO]: [Origins-Bukkit]                |___/
[21:04:47 INFO]: [Origins-Bukkit]
[21:04:47 INFO]: [Origins-Bukkit] Server running Paper version git-Paper-145 (MC: 1.18.1)
[21:04:47 INFO]: [Origins-Bukkit] (Implementing API version git-Paper-145 (MC: 1.18.1))
[21:04:47 INFO]: [Origins-Bukkit]
[21:04:47 INFO]: [Origins-Bukkit] Supported Server Version Detected. Initializing!
[21:04:47 INFO]: [Origins-Bukkit] Checking dependencies...
[21:04:47 INFO]: [Origins-Bukkit] ProtocolLib found! Hooking...
[21:04:47 INFO]: [Origins-Bukkit] PancakeLibCore found! Hooking...
[21:04:47 INFO]: [Origins-Bukkit] Loading files...
[21:04:47 INFO]: [Origins-Bukkit] The config.yml file was not found. Creating one...
[21:04:47 INFO]: [Origins-Bukkit] Successfully created the config.yml file
[21:04:47 INFO]: [Origins-Bukkit] The lang.yml file was not found. Creating one...
[21:04:47 INFO]: [Origins-Bukkit] Successfully created the lang.yml file
[21:04:47 INFO]: [Origins-Bukkit] Successfully loaded the files.
[21:04:47 INFO]: [Origins-Bukkit] Plugin has been enabled!
[21:04:47 INFO]: Running delayed init tasks
[21:04:47 INFO]: [Essentials] Fetching version information...
[21:04:47 INFO]: Done (3.761s)! For help, type "help"
[21:04:47 INFO]: Timings Reset
[21:04:57 INFO]: [Origins-Bukkit] Checking for updates...
[21:04:57 INFO]: [Origins-Bukkit] No updates found.
[21:05:11 INFO]: UUID of player Pseudolime is 94c1c964-088c-4357-80ee-dd2fcccaa039
[21:05:11 ERROR]: Could not pass event PlayerJoinEvent to Origins-Bukkit vBuild 3-ALPHA
java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
	at jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64) ~[?:?]
	at jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70) ~[?:?]
	at jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266) ~[?:?]
	at java.util.Objects.checkIndex(Objects.java:359) ~[?:?]
	at java.util.ArrayList.get(ArrayList.java:427) ~[?:?]
	at me.lemonypancakes.originsbukkit.listeners.player.JoinEventListener.onJoin(JoinEventListener.java:46) ~[Origins-Bukkit Build 3-ALPHA.jar:?]
	at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:git-Paper-145]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at net.minecraft.server.players.PlayerList.postChunkLoadJoin(PlayerList.java:359) ~[paper-1.18.1.jar:git-Paper-145]
	at net.minecraft.server.players.PlayerList.lambda$placeNewPlayer$1(PlayerList.java:301) ~[paper-1.18.1.jar:git-Paper-145]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.tick(ServerGamePacketListenerImpl.java:308) ~[?:?]
	at net.minecraft.network.Connection.tick(Connection.java:526) ~[?:?]
	at net.minecraft.server.network.ServerConnectionListener.tick(ServerConnectionListener.java:201) ~[?:?]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1636) ~[paper-1.18.1.jar:git-Paper-145]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:480) ~[paper-1.18.1.jar:git-Paper-145]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1470) ~[paper-1.18.1.jar:git-Paper-145]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1264) ~[paper-1.18.1.jar:git-Paper-145]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.1.jar:git-Paper-145]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[21:05:11 INFO]: Pseudolime joined the game
[21:05:11 INFO]: Pseudolime[/192.168.1.4:49408] logged in with entity id 300 at ([world]579.3678930014279, 65.0, 276.6697535314527)
[21:05:15 INFO]: Pseudolime lost connection: Disconnected
```

**Comment by Carbolemons** [comment]
I was able to build and run this project using commit #c6bea5a966cf5806d1e9c6fdd277f90b63c99f6f (Build 2-RELEASE)

I figured I was using your Latest commits, which include your testing for build 3.

https://github.com/lemonypancakes/origins-bukkit/commit/c6bea5a966cf5806d1e9c6fdd277f90b63c99f6f

For anyone else possibly looking at this ticket
### Build Instructions

##Clone repository
`git clone https://github.com/lemonypancakes/origins-bukkit`
`git checkout c6bea5a966cf5806d1e9c6fdd277f90b63c99f6f``

##Download PacketWrapper (Build 71): 
- https://ci.dmulloy2.net/job/PacketWrapper/71/
Move Here: 
- `origins-bukkit/plugin/libs/PacketWrapper #71.jar`

##Download BuildTools
- https://www.spigotmc.org/wiki/buildtools/
> `java -jar BuildTools.jar --rev 1.18 --remapped`
copy `Spigot/Spigot-Server/target/spigot-1.18-R0.1-SNAPSHOT-remapped-mojang.jar`
to  `origins-bukkit/v1_17_R1/spigot-1.18-R0.1-SNAPSHOT-remapped-mojang.jar`

> `java -jar BuildTools.jar --rev 1.17.1 --remapped`
copy `Spigot/Spigot-Server/target/spigot-1.17.1-R0.1-SNAPSHOT-remapped-mojang.jar`
to  `origins-bukkit/v1_17_R1/spigot-1.17.1-R0.1-SNAPSHOT-remapped-mojang.jar`

## Open project
origins-bukkit/pom.xml

`mvn clean install`


Thank you so much for your help! A very neat plugin so far, and my friends are enjoying it. Take care!
