### ISSUE TITLE
Please add 1.18.2 support

### ISSUE THREAD

**Issue by unxw** [lemonypancakes/origins-bukkit#24]
### Minecraft Server's Version and Software

I use aternos to host my server, however, it sucks that i cant use this amazing plugin on the new mc version. Its alright though, just wishing for an update. :)   (btw devs you did an amazing job) :

### Plugin's Version

Build 2-RELEASE

### Bug Description

simply wishing for an update

### To Reproduce

download the plugin on a newer version of minecraft

**Comment by Lebyy** [comment]
Can you post the error log which you encounter?

**Comment by YouKnwNothing** [comment]
> 
![og ic](https://user-images.githubusercontent.com/92229785/162602467-c919e3c5-8e68-4e7f-b019-fd7591e15262.PNG)

**Comment by unxw** [comment]
I'm going to check if I get the same issues as well. I am going to send an error log in like 20 min.

**Comment by unxw** [comment]
https://mclo.gs/fw08dZT logs here

**Comment by Hexidecimark** [comment]
`[22:11:29] [Server thread/INFO]: [Origins-Bukkit] Enabling Origins-Bukkit vBuild 2-RELEASE
[22:11:29] [Server thread/INFO]: [0;36;22m[Origins-Bukkit] [0;31;22m   ___       _       _                 ____        _    _    _ _[m
[22:11:29] [Server thread/INFO]: [0;36;22m[Origins-Bukkit] [0;31;1m  / _ \ _ __(_) __ _(_)_ __  ___      | __ ) _   _| | _| | _(_) |_[m
[22:11:29] [Server thread/INFO]: [0;36;22m[Origins-Bukkit] [0;33;22m | | | | '__| |/ _` | | '_ \/ __|_____|  _ \| | | | |/ / |/ / | __|[m
[22:11:29] [Server thread/INFO]: [0;36;22m[Origins-Bukkit] [0;33;1m | |_| | |  | | (_| | | | | \__ \_____| |_) | |_| |   <|   <| | |_[m
[22:11:29] [Server thread/INFO]: [0;36;22m[Origins-Bukkit] [0;32;1m  \___/|_|  |_|\__, |_|_| |_|___/     |____/ \__,_|_|\_\_|\_\_|\__|[m
[22:11:29] [Server thread/INFO]: [0;36;22m[Origins-Bukkit] [0;36;1m               |___/[m
[22:11:29] [Server thread/INFO]: [0;36;22m[Origins-Bukkit][m
[22:11:29] [Server thread/INFO]: [0;36;22m[Origins-Bukkit] [0;36;22mServer running [0;33;22mSpigot [0;36;22mversion [0;33;22m3480-Spigot-42b6152-cf391b5 (MC: 1.18.2)[m
[22:11:29] [Server thread/INFO]: [0;36;22m[Origins-Bukkit] [0;36;22m(Implementing API version [0;33;22m3480-Spigot-42b6152-cf391b5 (MC: 1.18.2)[0;36;22m)[m
[22:11:29] [Server thread/INFO]: [0;31;22m[Origins-Bukkit] Unsupported Server Version Detected! Safely disabling plugin...[m
[22:11:29] [Server thread/INFO]: [0;31;1m[Origins-Bukkit] Unregistered all item recipes.[m
[22:11:29] [Server thread/ERROR]: Error occurred while enabling Origins-Bukkit vBuild 2-RELEASE (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "me.lemonypancakes.originsbukkit.storage.StorageHandler.getOriginsPlayerData()" because the return value of "me.lemonypancakes.originsbukkit.OriginsBukkit.getStorageHandler()" is null
	at me.lemonypancakes.originsbukkit.api.wrappers.OriginPlayer.findOriginsPlayerData(OriginPlayer.java:75) ~[?:?]
	at me.lemonypancakes.originsbukkit.OriginsBukkit.onDisable(OriginsBukkit.java:228) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[spigot-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at me.lemonypancakes.originsbukkit.OriginsBukkit.disablePlugin(OriginsBukkit.java:412) ~[?:?]
	at me.lemonypancakes.originsbukkit.util.ServerVersionChecker.checkServerVersionCompatibility(ServerVersionChecker.java:120) ~[?:?]
	at me.lemonypancakes.originsbukkit.OriginsBukkit.checkServerCompatibility(OriginsBukkit.java:243) ~[?:?]
	at me.lemonypancakes.originsbukkit.OriginsBukkit.onEnable(OriginsBukkit.java:206) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342) ~[spigot-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[spigot-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:518) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3480-Spigot-42b6152-cf391b5]
	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:432) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3480-Spigot-42b6152-cf391b5]
	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.reload(CraftServer.java:917) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3480-Spigot-42b6152-cf391b5]
	at org.bukkit.Bukkit.reload(Bukkit.java:801) ~[spigot-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:27) ~[spigot-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[spigot-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.dispatchCommand(CraftServer.java:826) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3480-Spigot-42b6152-cf391b5]
	at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1957) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3480-Spigot-42b6152-cf391b5]
	at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1796) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3480-Spigot-42b6152-cf391b5]
	at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1777) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3480-Spigot-42b6152-cf391b5]
	at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:46) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3480-Spigot-42b6152-cf391b5]
	at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3480-Spigot-42b6152-cf391b5]
	at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:31) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3480-Spigot-42b6152-cf391b5]
	at net.minecraft.server.TickTask.run(SourceFile:18) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3480-Spigot-42b6152-cf391b5]
	at net.minecraft.util.thread.IAsyncTaskHandler.d(SourceFile:157) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3480-Spigot-42b6152-cf391b5]
	at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(SourceFile:23) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3480-Spigot-42b6152-cf391b5]
	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1190) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3480-Spigot-42b6152-cf391b5]
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:1) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3480-Spigot-42b6152-cf391b5]
	at net.minecraft.util.thread.IAsyncTaskHandler.y(SourceFile:131) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3480-Spigot-42b6152-cf391b5]
	at net.minecraft.server.MinecraftServer.be(MinecraftServer.java:1169) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3480-Spigot-42b6152-cf391b5]
	at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:1162) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3480-Spigot-42b6152-cf391b5]
	at net.minecraft.util.thread.IAsyncTaskHandler.c(SourceFile:140) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3480-Spigot-42b6152-cf391b5]
	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1146) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3480-Spigot-42b6152-cf391b5]
	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1051) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3480-Spigot-42b6152-cf391b5]
	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:304) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3480-Spigot-42b6152-cf391b5]
	at java.lang.Thread.run(Thread.java:833) [?:?]
`

**Comment by Hexidecimark** [comment]
https://mclo.gs/hQ9MDES#L1269
Identical error.

**Comment by lemonypancakes** [comment]
The new version is coming sometime this week.

**Comment by lemonypancakes** [comment]
https://www.spigotmc.org/resources/origins-bukkit-1-17-1-19.97926/
Commit: 80d09b6f493eaad639b4d0dff46c63875843b788
