### ISSUE TITLE
Merling Advantages not working, just the water breathing.

### ISSUE THREAD

**Issue by LazyThursday** [lemonypancakes/origins-bukkit#27]
### Minecraft Server's Version and Software

Minecraft: 1.19
Server: papermc [#8029]

### Plugin's Version

Build 3-ALPHA

### Bug Description

Merling's speed boost, night vision, aqua afinity, and staying still in water don't work.

Not sure if this is the cause but the console keeps getting spammed with:

[16:58:19 WARN]: [Origins-Bukkit] Plugin Origins-Bukkit vBuild 3-ALPHA generated an exception while executing task 25
java.lang.NoClassDefFoundError: com/comphenix/packetwrapper/WrapperPlayServerEntityMetadata
        at me.lemonypancakes.originsbukkit.factory.power.regular.CraftWaterBreathingPower$1.lambda$run$0(CraftWaterBreathingPower.java:30) ~[Origins.jar:?]
        at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
        at me.lemonypancakes.originsbukkit.factory.power.regular.CraftWaterBreathingPower$1.run(CraftWaterBreathingPower.java:29) ~[Origins.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.jar:git-Paper-32]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.19.jar:git-Paper-32]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.19.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ClassNotFoundException: com.comphenix.packetwrapper.WrapperPlayServerEntityMetadata

### To Reproduce

Launch the server then let a player (only happens when someone is in the server) to see the exception.

**Comment by lemonypancakes** [comment]
Try using the latest dev build of ProtocolLib https://ci.dmulloy2.net/job/ProtocolLib/

**Comment by lemonypancakes** [comment]
Fixed in the new version.

**Comment by LazyThursday** [comment]
Thx, console stopped spamming and the advantages came back.
