### ISSUE TITLE
Spam in console (warns)

### ISSUE THREAD

**Issue by Lacosst0** [LemonyPancakes/Origins-Bukkit#44]
### Minecraft Server's Version and Software

Purpur 1.19.1
/icanhasbukkit:
Current: git-Purpur-1743 (MC: 1.19.1)*
Previous: git-Purpur-1741 (MC: 1.19.1)
* You are running the latest version

Velocity proxy

Offline mode

### Plugin's Version

Origins-Bukkit 2.3.6
LemonCommonLib 2.2.0

Other plugins: 
Server Utils (and other)
![изображение](https://user-images.githubusercontent.com/68904262/181906712-ee3ac070-e881-43f5-a42a-1dd8afbc7c1e.png)

### Bug Description

After using Enderman pearl ability, console will be spammed with the same warn

```
[14:37:05 WARN]: [Origins-Bukkit] Plugin Origins-Bukkit v2.3.6 generated an exception while executing task 50
java.lang.NoSuchMethodError: 'void net.minecraft.network.protocol.game.ClientboundSystemChatPacket.<init>(net.minecraft.network.chat.IChatBaseComponent, int)'
        at me.lemonypancakes.bukkit.common.actionbarapi.v1_19_R1.CraftActionBar.sendMessage(CraftActionBar.java:31) ~[LemonCommonLib 2.2.0.jar:?]
        at me.lemonypancakes.bukkit.common.actionbarapi.ActionBarAPI.sendMessage(ActionBarAPI.java:55) ~[LemonCommonLib 2.2.0.jar:?]
        at me.lemonypancakes.bukkit.origins.factory.power.CraftCooldownPower$1.run(CraftCooldownPower.java:56) ~[Origins-Bukkit.2.3.6.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.19.1.jar:git-Purpur-1743]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[purpur-1.19.1.jar:git-Purpur-1743]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[purpur-1.19.1.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

Yeah...
![изображение](https://user-images.githubusercontent.com/68904262/181906765-510eeb98-402c-49de-85f1-a777cd8a6123.png)

### To Reproduce

Pick Enderman
Use pearl ability (F)
Check console

### Additional Information

If you change your origin, warns will still appear
Warns will stop, only after server reload
Origins plugin downloaded from github
LemonCommonLib downloaded from spigot

And yes, this plugin is just incredible! 
I do not know why it is not so popular :<

**Comment by Lacosst0** [comment]
I also found, that, for some reason, "Plugin Origins-Bukkit v2.3.6 generated an exception while executing task 50" can change to another number (21, 25)

If player leave the server, warns will still appear

**Comment by LemonyPancakes** [comment]
Try using the latest version of LemonCommonLib https://www.spigotmc.org/resources/lemoncommonlib-1-7-1-19-1.97522/

**Comment by Lacosst0** [comment]
> Try using the latest version of LemonCommonLib https://www.spigotmc.org/resources/lemoncommonlib-1-7-1-19-1.97522/

Omg it works, you are the best, keep it up! I think this is one of the most unique and best plugin! <3

**Comment by LemonyPancakes** [comment]
> > Try using the latest version of LemonCommonLib https://www.spigotmc.org/resources/lemoncommonlib-1-7-1-19-1.97522/
> 
> Omg it works, you are the best, keep it up! I think this is one of the most unique and best plugin! <3

Thx <3
