### ISSUE TITLE
Origins error on Paper 1.19.2

### ISSUE THREAD

**Issue by VelonacepsCalyxEggs** [LemonyPancakes/Origins-Bukkit#51]
### Minecraft Server's Version and Software

   Version:
    ProtocolLib v4.8.0
  Java Version:
    17.0.3.1
  Server:
    git-Paper-127 (MC: 1.19.2)
  OS:
    Windows 10.

### Plugin's Version

Origins-Bukkit 2.3.8

### Bug Description

When a player joins the game and choses an origin, an error starts appearing in both chat and console and it loops. Howver everything seems to be working fine.
```
  If this problem hasn't already been reported, please open a ticket
  at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
  Stack Trace:
  java.lang.IllegalArgumentException: Unable to find a field null with the type com.mojang.authlib.GameProfile in net.minecraft.network.protocol.login.PacketLoginInStart
  	at ProtocolLib.jar//com.comphenix.protocol.reflect.FuzzyReflection.getFieldByType(FuzzyReflection.java:397)
  	at ProtocolLib.jar//com.comphenix.protocol.reflect.accessors.Accessors.getFieldAccessor(Accessors.java:57)
  	at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ChannelInjector.handleLogin(ChannelInjector.java:658)
  	at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ChannelInjector.decode(ChannelInjector.java:591)
  	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:510)
  	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:449)
  	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:279)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
  	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
  	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327)
  	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:299)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
  	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
  	at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ChannelInjector$2.channelRead(ChannelInjector.java:292)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
  	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
  	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327)
  	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:299)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
  	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
  	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
  	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
  	at io.netty.handler.flush.FlushConsolidationHandler.channelRead(FlushConsolidationHandler.java:152)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
  	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
  	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
  	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
  	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
  	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722)
  	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)
  	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)
  	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
  	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995)
  	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
  	at java.base/java.lang.Thread.run(Thread.java:833)
  Dump:
  Parameters: 
    io.netty.buffer.PooledUnsafeDirectByteBuf@60b7b2d[
      memoryAddress=2869401317456
      recyclerHandle=io.netty.util.Recycler$DefaultHandle@7ce19bef
      chunk=Chunk(6062722f: 12%, 491520/4194304)
      handle=12947878993461249
      memory=java.nio.DirectByteBuffer[pos=0 lim=4194304 cap=4194304]
      offset=188432
      length=10
      maxLength=16
      cache=io.netty.buffer.PoolThreadCache@3cb7f652
      tmpNioBuf=<null>
      allocator=PooledByteBufAllocator(directByDefault: true)
      refCnt=2
      readerIndex=10
      writerIndex=10
      markedReaderIndex=0
      markedWriterIndex=0
      maxCapacity=2147483647
    ]
    manager:
      com.comphenix.protocol.injector.PacketFilterManager@38e081c5[
        unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@5862df1d
        packetListeners=[PacketAdapter[plugin=Origins-Bukkit, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=NORMAL, packets=[BLOCK_DIG[class=PacketPlayInBlockDig, id=26]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=Origins-Bukkit, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=NORMAL, packets=[BLOCK_DIG[class=PacketPlayInBlockDig, id=26]], gamephase=PLAYING, options=[]]]]
        packetInjector=com.comphenix.protocol.injector.netty.ProtocolInjector$5@20512a80
        playerInjection=com.comphenix.protocol.injector.netty.ProtocolInjector$4@2c97e99a
        inputBufferedPackets=[]
        recievedListeners=com.comphenix.protocol.injector.SortedPacketListenerList@10c5ab64
        sendingListeners=com.comphenix.protocol.injector.SortedPacketListenerList@5e111456
        hasClosed=false
        classLoader=PluginClassLoader{plugin=ProtocolLib v4.8.0, pluginEnabled=true, url=plugins\ProtocolLib.jar}
        reporter=com.comphenix.protocol.ProtocolLib$1@6475dc7a
        server=CraftServer{serverName=Paper,serverVersion=git-Paper-127,minecraftVersion=1.19.2}
        library=ProtocolLib v4.8.0
        asyncFilterManager=com.comphenix.protocol.async.AsyncFilterManager@fb3c9c3
        knowsServerPackets=true
        knowsClientPackets=true
        phaseLoginCount=0
        phasePlayingCount=2
        packetCreation=false
        nettyInjector=com.comphenix.protocol.injector.netty.ProtocolInjector@2530fe69
        pluginVerifier=com.comphenix.protocol.injector.PluginVerifier@3d1f21f8
        hasRecycleDistance=true
        minecraftVersion=(MC: 1.19.2)
        debug=false
      ]
  Sender:
    com.comphenix.protocol.injector.netty.ChannelInjector@b004b80[
      decodeBuffer=protected void net.minecraft.network.PacketDecoder.decode(io.netty.channel.ChannelHandlerContext,io.netty.buffer.ByteBuf,java.util.List) throws java.lang.Exception
      encodeBuffer=protected void net.minecraft.network.PacketEncoder.encode(io.netty.channel.ChannelHandlerContext,java.lang.Object,io.netty.buffer.ByteBuf) throws java.lang.Exception
      factory=com.comphenix.protocol.injector.netty.InjectionFactory@3f1c755e
      player=CraftPlayer{name=obi_wan_kenobi}
      updated=<null>
      playerName=obi_wan_kenobi
      playerConnection=<null>
      networkManager=net.minecraft.network.NetworkManager@2058a12e
      originalChannel=[id: 0x96f146ff, L:/95.31.138.156:55045 - R:/95.31.138.156:51216]
      channelField=VolatileField [accessor=DefaultFieldAccessor [field=public io.netty.channel.Channel net.minecraft.network.NetworkManager.m], container=net.minecraft.network.NetworkManager@2058a12e, previous=[id: 0x96f146ff, L:/95.31.138.156:55045 - R:/95.31.138.156:51216], current=com.comphenix.protocol.injector.netty.ChannelInjector$3@76970ef3, previousLoaded=true, currentSet=true, forceAccess=true]
      packetMarker={}
      currentEvent=<null>
      finalEvent=<null>
      unfilteredProcessedPackets=com.comphenix.protocol.injector.netty.PacketFilterQueue@179dd7e7
      vanillaDecoder=net.minecraft.network.PacketDecoder@5933a371
      vanillaEncoder=net.minecraft.network.PacketEncoder@230495d
      finishQueue=[]
      channelListener=com.comphenix.protocol.injector.netty.ProtocolInjector@2530fe69
      processor=com.comphenix.protocol.injector.NetworkProcessor@1fd92aa3
      injected=true
      closed=false
      cumulation=PooledUnsafeDirectByteBuf(ridx: 10, widx: 10, cap: 10)
      cumulator=io.netty.handler.codec.ByteToMessageDecoder$1@5b352a02
      singleDecode=false
      first=true
      firedChannelRead=false
      selfFiredChannelRead=true
      decodeState=1
      discardAfterReads=16
      numReads=0
      added=true
    ]
  Version:
    ProtocolLib v4.8.0
  Java Version:
    17.0.3.1
  Server:
    git-Paper-127 (MC: 1.19.2)

```

### To Reproduce

Well, I am really not sure, run papermc server with Origins?

**Comment by LemonyPancakes** [comment]
Use the latest dev build of ProtocolLib https://ci.dmulloy2.net/job/ProtocolLib/lastSuccessfulBuild/

**Comment by VelonacepsCalyxEggs** [comment]
> Use the latest dev build of ProtocolLib https://ci.dmulloy2.net/job/ProtocolLib/lastSuccessfulBuild/

Thanks! That indeed was the problem, I recommend updating the link to ProtocolLib on Bukkit to avoid this kind of stuff, Thank you!
