### ISSUE TITLE
Server crash with /origin set

### ISSUE THREAD

**Issue by Thatsmusic99** [LemonyPancakes/Origins-Bukkit#64]
### Minecraft Server's Version and Software

This server is running Paper version git-Paper-216 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: 30cb7d0)
You are running the latest version
Previous version: git-Paper-136 (MC: 1.16.1)

### Plugin's Version

2.3.8

### Bug Description

When using the /origin set command, the server will crash and restart due to what looks like something set up incorrectly within LemonCommonLib:

```
java.lang.NoSuchMethodError: 'net.minecraft.resources.MinecraftKey net.minecraft.commands.arguments.ArgumentMinecraftKeyRegistered.e(com.mojang.brigadier.context.CommandContext, java.lang.String)'
	at LemonCommonLib 2.2.2.jar//me.lemonypancakes.bukkit.common.dev.jorel.commandapi.nms.NMS_Common.getMinecraftKey(NMS_Common.java:546)
	at LemonCommonLib 2.2.2.jar//me.lemonypancakes.bukkit.common.dev.jorel.commandapi.arguments.NamespacedKeyArgument.parseArgument(NamespacedKeyArgument.java:64)
	at LemonCommonLib 2.2.2.jar//me.lemonypancakes.bukkit.common.dev.jorel.commandapi.arguments.NamespacedKeyArgument.parseArgument(NamespacedKeyArgument.java:38)
	at LemonCommonLib 2.2.2.jar//me.lemonypancakes.bukkit.common.dev.jorel.commandapi.arguments.CustomArgument.parseArgument(CustomArgument.java:137)
	at LemonCommonLib 2.2.2.jar//me.lemonypancakes.bukkit.common.dev.jorel.commandapi.CommandAPIHandler.parseArgument(CommandAPIHandler.java:390)
	at LemonCommonLib 2.2.2.jar//me.lemonypancakes.bukkit.common.dev.jorel.commandapi.CommandAPIHandler.generatePreviousArguments(CommandAPIHandler.java:919)
	at LemonCommonLib 2.2.2.jar//me.lemonypancakes.bukkit.common.dev.jorel.commandapi.CommandAPIHandler.lambda$toSuggestions$7(CommandAPIHandler.java:943)
	at com.mojang.brigadier.tree.ArgumentCommandNode.listSuggestions(ArgumentCommandNode.java:71)
	at com.mojang.brigadier.CommandDispatcher.getCompletionSuggestions(CommandDispatcher.java:600)
	at com.mojang.brigadier.CommandDispatcher.getCompletionSuggestions(CommandDispatcher.java:580)
	at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleCustomCommandSuggestions$5(ServerGamePacketListenerImpl.java:835)
	at net.minecraft.server.TickTask.run(TickTask.java:18)
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149)
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23)
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1423)
	at net.minecraft.server.MinecraftServer.c(MinecraftServer.java:189)
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:122)
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1400)
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1393)
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:132)
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1371)
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1277)
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

### To Reproduce

Attempt to run the command `/origin set @p origins-bukkit:origin` in-game - only, for the server to crash before you can enter anything else.

**Comment by Thatsmusic99** [comment]
Probably correlation vs causation but bumping the CommandAPI to v8.5.1 in LemmonCommonLib seems to fix this.
